### ISSUE TITLE
TypeScript declarations

### ISSUE THREAD

**Issue by buffcode** [node-modbus/stream#22]
Hi,

first of all thanks to you for your solid work!

We are planning to use your library within one of our TypeScript-based projects and noticed that there aren't any type declarations yet.
I'm willing to provide those declarations and it would be nice when some one could test / extend the types to include serial and UDP, as we probably only use either TCP or UDP in our project.

I will publish the types in my own repository first of all and if everything looks okay a PR to the official [@types](https://www.npmjs.com/~types) namespace managed by https://github.com/DefinitelyTyped/DefinitelyTyped will be created.

There are no changes to the actual codebase necessary, though this project would really benefit from a migration to typescript (codecompletion for driver / stream options etc.)

**Comment by dresende** [comment]
Thank you. When you have it ready, just pull it here 👍
