### ISSUE TITLE
Improvement of responses length check robustness

### ISSUE THREAD

**Issue by ZupoLlask** [node-modbus/stream#23]
Hi!

While debugging a project, I stumbled upon the following lines of code:

- https://github.com/node-modbus/stream/blob/master/lib/transport/tcp.js#L79
- https://github.com/node-modbus/stream/blob/master/lib/transport/ascii.js#L45

Is there any good reason for not making a "not equal" comparison here?

Although it may seem exaggerated that may guard us a little bit better from malicious crafted responses.

Thanks.

**Comment by dresende** [comment]
> Is there any good reason for not making a "not equal" comparison here?

Because that's exactly what we want. Your change would require an extra packet byte before being able to parse the previous one, which does not make sense.
