### ISSUE TITLE
[webpack] Module not found: Error: Can't resolve 'serialport/package'

### ISSUE THREAD

**Issue by hxl-dy** [node-modbus/stream#26]
```
ERROR in ./node_modules/modbus-stream/lib/driver/serial.js
Module not found: Error: Can't resolve 'serialport/package'
```

**Comment by dresende** [comment]
What version are you using and in what system are you trying?

**Comment by hxl-dy** [comment]
windows 10
webpack@^3

**Comment by dresende** [comment]
I'm not sure I can help as I don't use Windows. Are you able to just create a folder and install `serialport` package there?

**Comment by hxl-dy** [comment]
I have installed serialport@7.0.2, but the error still occur.

**Comment by dresende** [comment]
Never tried above version `6.0.0` and never done it on Windows, can't help you 😢

**Comment by hxl-dy** [comment]
fixed: add this config to webpack config:
```javascript
module.exports = {
  resolve: {
    extensions: ['.json', '.ts', '.js'],
  },
}
```
Because [this line](https://github.com/node-modbus/stream/blob/master/lib/driver/serial.js#L1) does not use `.json` explicitly.
