### ISSUE TITLE
How to remove debugging?

### ISSUE THREAD

**Issue by tgirotto** [node-modbus/stream#45]
I have tried setting the debug field to null and false in the extra option when reading from holding registers with no luck. 

```
connection.readHoldingRegisters ({address : address, quantity : 1, extra: { unitId: slave, debug: false} }, (err, res) => {
     console.log(res);
})

```

However, I keep getting the following:

```
2019-09-06T16:13:38.543Z << undefined 0x[ 00, 1B, 00, 00, 00, 06, 02, 03, 00, 5E, 00, 01 ]
```

Is it expected behaviour?

**Comment by Nedgeva** [comment]
Just pass `{ debug: null }` as connection options.

**Comment by Nedgeva** [comment]
Just pass `{ debug: null }` as connection options.
