### ISSUE TITLE
turning off debugging in console?

### ISSUE THREAD

**Issue by gregoryZajac** [node-modbus/stream#49]
Hi
I'm getting an array of buffers of registers with every connection.readHoldingRegisters call.
It looks like:
`2019-11-04T22:11:33.896Z >> server-node 0x[ 00, 01, 00, 00, 00, DD, 01, 03, DA........`
How can I turn off please? Thank you

**Comment by dresende** [comment]
Show me your code to connect or to listen for connections.

**Comment by dresende** [comment]
There's an option `debug` that you can set to `null` to avoid debugging (or a string of your choice to enable debug with that prefix).

**Comment by gregoryZajac** [comment]
`  modbus.tcp.connect(502, ip, { debug: null }, (err, connection) => {....`
debug set to null, as above, turned off the logging messages, thank you!
