### ISSUE TITLE
Avoid use of `package` (future reserved word)

### ISSUE THREAD

**Issue by jacobq** [node-modbus/stream#5]
This isn't a huge deal, but I noticed that you used `package` as an identifier in several places--most significantly in example code. This causes problems for people using `strict` mode (common when using [babel](https://babeljs.io/)). It would be nice if you could use some other name that is not a [future reserved word in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Future_reserved_keywords).

**Comment by dresende** [comment]
You're right. I'll probably fix it later today.

**Comment by dresende** [comment]
I looked now and I just use it on tests and the example 😄
