### ISSUE TITLE
I Don't understanding is problem, please recommend to me. Thanks

### ISSUE THREAD

**Issue by khomkrit01** [node-modbus/stream#61]
Refusing to install package with name "modbus-stream" under a package
npm ERR! also called "modbus-stream". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

**Comment by dresende** [comment]
Open you `package.json` and rename your project. You can't have a project with the same name as a published package.

**Comment by khomkrit01** [comment]
yes this work, thank you so much
