### ISSUE TITLE
How to set socket options for ModbusTCP connection? (e.g. keep-alive)

### ISSUE THREAD

**Issue by jacobq** [node-modbus/stream#62]
I have a case where I'm communicating with a ModbusTCP slave device, and its firmware appears to close TCP connections that have been idle for ~5 minutes. Is there a way to access the underlying `socket` without reaching in too deeply? Looks like I can do this via `connection.transport.stream`, e.g.

```js
modbus.tcp.connect(port, host, { debug: '...' }, (err, connection) => {
  connection.transport.stream.setKeepAlive(true);
  // ...
});
``` 

Is this OK / is this part of the public / stable API from `modbus-stream`?

**Comment by dresende** [comment]
Yes, it's OK as long as you ensure you're always using TCP. We'll not break any of those paths, the module looks stable and will not probably change much, just fixes and polishing.
