### ISSUE TITLE
Query three different registers

### ISSUE THREAD

**Issue by Aaqu** [node-modbus/stream#69]
I am new to modbus stream, how to query three different registers (e.g. 1026, 1032, 1552) on one connection. Need to use async / await?

**Comment by Aaqu** [comment]
I tried but it doesn't work for me
https://github.com/node-modbus/stream/issues/58#issuecomment-594571454

**Comment by dresende** [comment]
Yes, you need something to handle multiple requests. You could use `quantity` parameter (see README) but in your case you would have to require 26 records.

**Comment by Aaqu** [comment]
Will an example be added to the documentation in the future?

**Comment by dresende** [comment]
It's there, you can just copy the readCoils example and change to holding registers or input registers.

```js
// for a serial connetion
modbus.serial.connect("/dev/ttyS123", { debug: "automaton-123" }, (err, connection) => {
    if (err) throw err;

    connection.readHoldingRegisters({ address: 1026, quantity: 26 }, (err, res) => {
        if (err) throw err;

        console.log(res.response.data); // response
    })
});
```

**Comment by Aaqu** [comment]
> It's there, you can just copy the readCoils example and change to holding registers or input registers.
> 
> ```js
> // for a serial connetion
> modbus.serial.connect("/dev/ttyS123", { debug: "automaton-123" }, (err, connection) => {
>     if (err) throw err;
> 
>     connection.readHoldingRegisters({ address: 1026, quantity: 26 }, (err, res) => {
>         if (err) throw err;
> 
>         console.log(res.response.data); // response
>     })
> });
> ```

I'm sorry, I thought async / await example, if I need 1020 and 1520, I don't want to download all 500 registers

**Comment by dresende** [comment]
Async / await is not supported for now (the code does not use Promises). What you can do instead is use module async with `async.series`.

```js
// for a serial connetion
modbus.serial.connect("/dev/ttyS123", { debug: "automaton-123" }, (err, connection) => {
    if (err) throw err;

    async.series([
        (next) => {
            connection.readHoldingRegisters({ address: 1020 }, (err, res) => {
                if (err) return next(err);

                console.log(res.response.data); // response

                return next();
            });
        },
        (next) => {
            connection.readHoldingRegisters({ address: 1520 }, (err, res) => {
                if (err) return next(err);

                console.log(res.response.data); // response

                return next();
            });
        },
    ], (err) => {
        // move on..
    });
});
```

**Comment by Aaqu** [comment]
Thank you for your help now I understand

**Comment by Aaqu** [comment]
What do you think about this solution?
```
function newTcpDateStream(port, ip, id, register, querys) {
    return new Promise(function (resolve) {
       // setTimeout(function () {
            modbus.tcp.connect(port, ip, { debug: "none", unitId: id }, (err, connection) => {
                connection.readInputRegisters({ address: register, quantity: querys }, (err, data) => {
                    connection.close();
                    resolve(data.response.data);
                });
            });
       // }, 10);
    });
}

async function streamTcp() {
    console.log(await newTcpDateStream(500, '192.168.1.1', 1, 1024, 5));
    console.log(await newTcpDateStream(500, '192.168.1.1', 1, 1536, 2));
    console.log(await newTcpDateStream(500, '192.168.1.1', 1, 1557, 2));
}

streamTcp();
```

**Comment by Aaqu** [comment]
Wow! without `setTimeout` also works, again thanks for help

**Comment by dresende** [comment]
That's good. You can also check for `err` and call `reject(err)` and you have full support for async (in this case, wrap your `streamTcp` code inside a try/catch).

**Comment by Aaqu** [comment]
Does `connectTimeout` also work for `readInputRegisters`?

**Comment by dresende** [comment]
Try option `retries` (number of times to repeat request before quitting) and `retry` (timeout before trying again).

```js
modbus.tcp.connect(port, "host", {
    retry   : 1000, // milliseconds = 1 second
    retries : 4,    // 1 try + 4 retries = 5 attempts
});
```
