### ISSUE TITLE
Error reading Modbus TCP/IP on a network

### ISSUE THREAD

**Issue by MiguelSeixas** [node-modbus/stream#70]
Hi,

When I try to read a value of a modbus TCP/IP device directly connected to it with a ethernet cable with the following code i receive the values correctly:

```
// create an empty modbus client
var ModbusRTU = require("modbus-serial");
var client = new ModbusRTU();

// open connection to a tcp line
client.connectTCP("172.29.20.136", { port: 502 });
client.setID(1);

// read the values of the register 41658 on device number 1. and log the values to the console.
setInterval(function() {
    client.readHoldingRegisters(41658, 1, function(err, data) {
        console.log(data.data);
    });
}, 100000);
```

But when I try to read the same device on the network, with multiple hops on different routers i receive the following error:

(node:1556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ETIMEDOUT 17
2.29.20.136:502
        console.log(data.data);
TypeError: Cannot read property 'data' of undefined

Does it mean that the program is terminated before a value is given to the data variable, or is the program unable to read data in diferent routers? I tested the connection with TRACERT and i found that the packages take about 45 ms from my router to the destination router.

**Comment by dresende** [comment]
I believe you're in the wrong repository. Perhaps you want this: https://github.com/yaacov/node-modbus-serial
