### ISSUE TITLE
Question: Trying to reset a count function

### ISSUE THREAD

**Issue by XavegX367** [node-modbus/stream#76]
Hello, I am really new to working with Modbus and I am trying to reset the amount of times a button is pressed. the count is already working, it gets stored into 2 bytes which I retrieve with the "readHoldingRegisters" function. But when I try to create a "Reset counter" button I assume I need to use the "WriteSingleRegister" function, but I am not really sure how to send the buffer.

This is how I read the clicks:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/76949970/207547974-18747b64-81d8-4d30-8ff7-077b1e052d76.png">

This is the response:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/76949970/207548127-1a652615-c908-4747-ad9b-8255f4e0763d.png">

The count function works by summing these 2 values after multiplying the 0 value by * 256. Value 0 and 1 need both to be set back to 0. Hopefully you are able to help.

Thanks in advance!

**Comment by dresende** [comment]
Check the `README`, there's the list of methods. For WriteSingleRegister (if the device supports it), you should send:

```js
connection.writeSingleRegister({ address: 0, value: Buffer.from([ 0x01, 0x02 ]) }, (err) => {
    // ...
});
```

If it doesn't support and instead only supports multiple registers, you can use:

```js
connection.writeMultipeRegisters({ address: 0, values: [ Buffer.from([ 0x01, 0x02 ]) ] }, (err) => {
    // ...
});
```

**Comment by XavegX367** [comment]
> Check the `README`, there's the list of methods. For WriteSingleRegister (if the device supports it), you should send:
> 
> ```js
> connection.writeSingleRegister({ address: 0, value: Buffer.from([ 0x01, 0x02 ]) }, (err) => {
>     // ...
> });
> ```
> 
> If it doesn't support and instead only supports multiple registers, you can use:
> 
> ```js
> connection.writeMultipeRegisters({ address: 0, values: [ Buffer.from([ 0x01, 0x02 ]) ] }, (err) => {
>     // ...
> });
> ```

Yes I figured, but how do I get it to set both of the values I showed in the screenshot above to set it to 0?

**Comment by dresende** [comment]
Oh.. I missed that. Because modbus registers hold 2 bytes, you can use buffer functions to read signed/unsigned integers of 16 bits with big/little endian.

In your example, assuming `b` is that buffer of bytes 0x01 and 0x2F (47):

```js
let b = Buffer.from([ 0x01, 0x2F ]);

console.log(b.readUInt16BE(0)); // should print 303

// if instead it's little endian:
console.log(b.readUInt16LE(0)); // should print 12033
```

**Comment by dresende** [comment]
The rest of the functions here:

https://nodejs.org/dist/latest-v18.x/docs/api/buffer.html

**Comment by XavegX367** [comment]
Thanks a lot, works like a charm!
